### ISSUE TITLE
having an unknown issue.

### ISSUE THREAD

**Issue by Omkhare632** [Fuenfgeld/HospitalNavigator#3]
Hi ,
please reply ASAP!
I am a first year computer science student ,
I have participated in an hackathon and has reffered to your your navigation project ,
I have qualified for final round and they need a prototype till 21st day of march
its been showing up some errors ,as I being a complete noob, 
I am unable to grasp the exact errors,
I have attached the jupyter file in JPG format,
and here are the errors'
this is showing up,
IndexError                                Traceback (most recent call last)
~\anaconda3\lib\site-packages\ipywidgets\widgets\interaction.py in update(self, *args)
    255                     value = widget.get_interact_value()
    256                     self.kwargs[widget._kwarg] = value
--> 257                 self.result = self.f(**self.kwargs)
    258                 show_inline_matplotlib_plots()
    259                 if self.auto_display and self.result is not None:

~\AppData\Local\Temp/ipykernel_18644/2319047822.py in selectHouse(way)
     65         displayWay('boyshostelno.8')
     66     if way=='canteen':
---> 67         displayWay('canteenpath')
     68     if way == 'cbuilding':
     69         displayWay('cbuilding' )

~\AppD
![universitynavigator](https://user-images.githubusercontent.com/101925005/159161446-6fb8606c-96a1-48b9-9d4b-ec128abae868.jpg)
ata\Local\Temp/ipykernel_18644/3482699911.py in displayWay(whereTo)
      1 def displayWay(whereTo):
----> 2      myNavigator.changeDestination(whereTo)

~\AppData\Local\Temp/ipykernel_18644/2464922385.py in changeDestination(self, newDestination)
     12     def changeDestination(self,newDestination):
     13         self.destination = newDestination
---> 14         self.redrawMap()
     15 
     16     def changeStartPoint(self, newStartPoint):

~\AppData\Local\Temp/ipykernel_18644/2464922385.py in redrawMap(self)
     46         print(f'position {self.position}, destination {self.destination}')
     47         sppuMap = folium.Map(location = self.sppuLocation, width = "75%", zoom_start = 17)
---> 48         self.drawPathWay(sppuMap)
     49         self.drawBuilding(sppuMap)
     50         display(sppuMap)

~\AppData\Local\Temp/ipykernel_18644/2464922385.py in drawPathWay(self, sppuMap)
     29         return coordinate
     30 
---> 31       searchString = self.position + self.destination.split('a building')[1]
     32       with open(self.geoResources[searchString]) as f:
     33            testWay = json.load(f)

IndexError: list index out of range

<function __main__.selectHouse(way)>
![universitynavigator](https://user-images.githubusercontent.com/101925005/159161454-dbc9be17-3d93-448a-bdeb-0dc5ad69f19d.jpg)
waiting eagrly for your reply!

**Comment by Fuenfgeld** [comment]
I cannot fix your bugs. next time don't send screenshots of code.
